### ISSUE TITLE
[bug] 没有判断这种情况, 会出现错误

### ISSUE THREAD

**Issue by liu2guang** [rtpkgs/buildpkg#13]
.\buildpkg.exe make https://github.com/cloudwu/coroutine

```
> .\buildpkg.exe make https://github.com/cloudwu/coroutine
[2018-09-25 17:39:09,292 buildpkg.py L0538 INFO    ]: << Start run buildpkg >>
[2018-09-25 17:39:09,293 buildpkg.py L0539 INFO    ]: Version      : v0.2.0
[2018-09-25 17:39:09,293 buildpkg.py L0540 INFO    ]: Author       : liu2guang
[2018-09-25 17:39:09,293 buildpkg.py L0541 INFO    ]: License      : GPLv3
[2018-09-25 17:39:09,293 buildpkg.py L0542 INFO    ]: Conteributors: {'liu2guang': 'https://github.com/liu2guang', 'balanceTWK': 'https://github.com/balanceTWK'}
[2018-09-25 17:39:09,293 buildpkg.py L0287 DEBUG   ]: Analyze the path to use:
[2018-09-25 17:39:09,293 buildpkg.py L0288 DEBUG   ]: - buildpkg_path
 : G:\embedded\GitHub\buildpkg
[2018-09-25 17:39:09,294 buildpkg.py L0289 DEBUG   ]: - buildpkg_template_path
 : G:\embedded\GitHub\buildpkg\templates
[2018-09-25 17:39:09,294 buildpkg.py L0290 DEBUG   ]: - buildpkg_packages_path
 : G:\embedded\GitHub\buildpkg\packages
[2018-09-25 17:39:09,294 buildpkg.py L0291 DEBUG   ]: - buildpkg_packages_xxx_path
 : G:\embedded\GitHub\buildpkg\packages\https://github.com/cloudwu/coroutine
[2018-09-25 17:39:09,294 buildpkg.py L0292 DEBUG   ]: - buildpkg_packages_xxx_example_path: G:\embedded\GitHub\buildpkg\packages\https://github.com/cloudwu/coroutine\example
[2018-09-25 17:39:09,294 buildpkg.py L0293 DEBUG   ]: - buildpkg_packages_xxx_scripts_path: G:\embedded\GitHub\buildpkg\packages\https://github.com/cloudwu/coroutine\scripts
[2018-09-25 17:39:09,295 buildpkg.py L0178 DEBUG   ]: Buildpkg load config:
{
    "username": "liu2guang",
    "list_ignore_inc": [
        ".git",
        "example",
        "doc",
        "test"
    ],
    "list_ignore_src": [
        "test.c",
        "example.c"
    ],
    "templates": {
        "readme_md": "template-readme-rtt.txt",
        "sconscript": "template-sconscript.txt",
        "sconscript_example": "template-sconscript-example.txt",
        "ci_github": "template-ci-github.txt",
        "kconfig": "template-kconfig.txt",
        "package_json": "template-package-json.txt"
    },
    "pkg_def_version": "v1.0.0",
    "commit_content": "[builpkg] Use the buildpkg tool to quickly build ${pkgname}'s packages!"
}
[2018-09-25 17:39:09,298 buildpkg.py L0267 INFO    ]: To complete self-check, and load config form [config.json] file.
[2018-09-25 17:39:09,298 buildpkg.py L0341 INFO    ]: Start make https://github.com/cloudwu/coroutine package.
Traceback (most recent call last):
  File "buildpkg\buildpkg.py", line 569, in <module>
  File "buildpkg\buildpkg.py", line 554, in main
  File "buildpkg\buildpkg.py", line 367, in _make_package
  File "os.py", line 211, in makedirs
  File "os.py", line 211, in makedirs
  File "os.py", line 211, in makedirs
  File "os.py", line 221, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'G:\\embedded\\GitHub\\buildpkg
\\packages\\https:'
[6908] Failed to execute script buildpkg
```

**Comment by balanceTWK** [comment]
哦几百块

**Comment by balanceTWK** [comment]
![default](https://user-images.githubusercontent.com/30776697/46016760-381b1c00-c108-11e8-90be-7bb456add599.png)
满头大汗.jpg

**Comment by liu2guang** [comment]
已经修复
